# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Om < Formula
  desc "A powerful CLI for scaffolding modern web applications."
  homepage "https://github.com/jashkahar/open-workbench-platform"
  version "0.5.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/jashkahar/open-workbench-platform/releases/download/v0.5.2/om_0.5.2_darwin_amd64.tar.gz"
      sha256 "b149d78e3b5e7ea168e453a0d544279fa6ef6667770592455b3dbf2148c53e7b"

      def install
        bin.install "om"
      end
    end
    on_arm do
      url "https://github.com/jashkahar/open-workbench-platform/releases/download/v0.5.2/om_0.5.2_darwin_arm64.tar.gz"
      sha256 "0e8c8b0f8579b1c72b539a9693a9f55f6eea40de48ebb953b00c6f430584bbe2"

      def install
        bin.install "om"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jashkahar/open-workbench-platform/releases/download/v0.5.2/om_0.5.2_linux_amd64.tar.gz"
        sha256 "2937fd19b4dff6bac4a49f94ddecfb6fff6c8fcc8d2a241228dbd59edeee86bd"

        def install
          bin.install "om"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jashkahar/open-workbench-platform/releases/download/v0.5.2/om_0.5.2_linux_arm64.tar.gz"
        sha256 "c37f7513dafe0cc6e1506686a76278fd69561e1a39424bd4d77cc8a94ac2f305"

        def install
          bin.install "om"
        end
      end
    end
  end

  test do
    system "#{bin}/om --version"
  end
end
